# docker run -d --name gitlab-runner --restart always \
# -v /var/run/docker.sock:/var/run/docker.sock \
# -v /srv/gitlab-runner/config:/etc/gitlab-runner \
# gitlab/gitlab-runner:latest
# 
version: '2.2'
services: 
  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
     - '/var/run/docker.sock:/var/run/docker.sock'
     - './config:/etc/gitlab-runner'